FROM rocker/r-ver:4.3.2 as backendbase

# install os dependencies
RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev \
  curl \
  libsodium-dev \
  libxml2-dev \
  && rm -rf /var/lib/apt/lists/*

# install pak alternatives to install.packages
RUN Rscript -e "install.packages('pak')"

FROM backendbase as backend
# install latest plumber from github main branch
RUN Rscript -e "pak::pkg_install('rstudio/plumber@main')"

# install other R packages
RUN Rscript -e "pak::pkg_install(c('logger','tictoc', 'fs', 'jsonlite','config'))"
RUN Rscript -e "pak::pkg_install(c('DBI','RPostgres','dbplyr','magrittr','yaml','pool','future','promises'))"

# setup workspace
COPY ./backend /app

WORKDIR /app

EXPOSE 8080

FROM backend as backend_testdb
ENTRYPOINT ["Rscript"]
CMD ["--vanilla", "app.R", "mydb_test"]

FROM backend as backend_devdb
ENTRYPOINT ["Rscript"]
CMD ["--vanilla", "app.R", "mydb_dev"]

FROM backendbase as test_backend

RUN Rscript -e "pak::pkg_install(c('testthat', 'httr', 'httr2'))"
# setup workspace
COPY ./tests/backend /app

WORKDIR /app

EXPOSE 8087


ENTRYPOINT ["Rscript"]
CMD ["test.R"]