###
## for local dev, wait for db to pass healthcheck before we start node
###

# version key is DEPRECATED
# v2 and v3 features now combined in compose CLI

services:
  postgres_db:
    build:
      dockerfile: ./Dockerfile_postgres
      context: .
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile_backend
      context: .
      target: backend_testdb
    environment:
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    container_name: backend_testdb
    volumes:
      - ./backend:/app
    networks:
      - my_network
    ports:
      - "8080:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/health-check/"]
      interval: 30s
      timeout: 5s
      retries: 2

  test_backend:
    build:
      dockerfile: Dockerfile_backend
      context: .
      target: test_backend
    container_name: test_backend
    volumes:
      - ./tests/backend:/app
    networks:
      - my_network
    ports:
      - "8087:8087"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_db:
    driver: local

networks:
  my_network:
    driver: bridge
